name: test
on: [push, pull_request]
jobs:
  cppcheck-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get -y update && sudo apt-get install -y cppcheck && \
        cppcheck . --force --inline-suppr
  build-test-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get -y update && sudo apt-get install -y build-essential
    - name: build
      run: |
        ./configure && make && make check
        timeout 300 src/iperf3 -s &
        ./test_commands.sh localhost
  build-test-ubuntu-20_04:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get -y update && sudo apt-get install -y build-essential 
    - name: build
      run: |
        ./configure && make && make check
        timeout 300 src/iperf3 -s &
        ./test_commands.sh localhost
