env:
  CIRRUS_CLONE_DEPTH: 5

freebsd_instance:
  image: freebsd-12-0-release-amd64
  image: freebsd-11-2-release-amd64
  image: freebsd-11-1-release-amd64
  image: freebsd-10-4-release-amd64

task:
  install_script: ci/before.sh
  script: ci/build.sh
