env:
  CIRRUS_CLONE_DEPTH: 5

freebsd_instance:
  image_family: freebsd-14-0-snap
  image_family: freebsd-13-1
  image_family: freebsd-13-0

task:
  install_script: sudo ci/install.sh
  script: ci/build.sh
